# Generated by Django 3.0.8 on 2020-07-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mou',
            old_name='image',
            new_name='img',
        ),
    ]
