# Generated by Django 3.0.8 on 2020-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_auto_20200710_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='img',
        ),
        migrations.AlterField(
            model_name='emailform',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
