# Generated by Django 3.0.8 on 2020-07-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_auto_20200710_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou',
            name='img',
            field=models.ImageField(null=True, upload_to='profilepics/'),
        ),
    ]
