# Generated by Django 3.0.8 on 2020-07-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_mou_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailform',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
