# Generated by Django 3.0.8 on 2020-07-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_auto_20200711_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='img',
        ),
    ]
