# Generated by Django 3.0.8 on 2020-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_remove_mou_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailForm',
        ),
        migrations.AddField(
            model_name='mou',
            name='img',
            field=models.ImageField(null=True, upload_to='profilepics/'),
        ),
    ]
