# Generated by Django 3.0.8 on 2020-07-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0009_auto_20200712_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='img',
        ),
    ]
