# Generated by Django 3.0.8 on 2020-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0014_auto_20200718_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectfile',
            name='file',
            field=models.CharField(choices=[('adminfile', 'Adminfile'), ('aplsafile', 'Aplsafile'), ('compliancefile', 'Compliancefile'), ('itfile', 'Itfile'), ('ruralfile', 'Ruralfile'), ('srfile', 'Srfile'), ('securityfile', 'Securityfile'), ('technologyfile', 'Technologyfile')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selectfile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='typeoffile',
            name='filetype',
            field=models.CharField(choices=[('adminfile', 'Adminfile'), ('aplsafile', 'Aplsafile'), ('compliancefile', 'Compliancefile'), ('itfile', 'Itfile'), ('ruralfile', 'Ruralfile'), ('srfile', 'Srfile'), ('securityfile', 'Securityfile'), ('technologyfile', 'Technologyfile')], max_length=50),
        ),
    ]
