# Generated by Django 3.0.8 on 2020-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0015_auto_20200718_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectfile',
            name='file',
            field=models.FileField(choices=[('adminfile', 'Adminfile'), ('aplsafile', 'Aplsafile'), ('compliancefile', 'Compliancefile'), ('itfile', 'Itfile'), ('ruralfile', 'Ruralfile'), ('srfile', 'Srfile'), ('securityfile', 'Securityfile'), ('technologyfile', 'Technologyfile')], max_length=50, null=True, upload_to=''),
        ),
    ]
