# Generated by Django 3.0.8 on 2020-07-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0016_auto_20200718_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
