# Generated by Django 3.0.8 on 2020-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0017_auto_20200718_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectfile',
            name='towhome',
        ),
        migrations.AddField(
            model_name='selectfile',
            name='towhom',
            field=models.CharField(choices=[('srinu1234', 'srinu1234')], max_length=100, null=True),
        ),
    ]
