# Generated by Django 3.0.8 on 2020-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0018_auto_20200719_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentuserdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_file', models.FileField(null=True, upload_to='')),
                ('u_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='selectfile',
            name='towhom',
            field=models.CharField(choices=[('srinu1234', 'srinu1234'), ('user1', 'user1')], max_length=100, null=True),
        ),
    ]
