# Generated by Django 3.0.8 on 2020-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0019_auto_20200719_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentuserdata',
            name='typeoffiles',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
