# Generated by Django 3.0.8 on 2020-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0020_documentuserdata_typeoffiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuserdata',
            name='u_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentuserdata',
            name='u_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
