# Generated by Django 3.0.8 on 2020-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0022_auto_20200719_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuserdata',
            name='u_file',
            field=models.FileField(null=True, upload_to='documentuser/'),
        ),
    ]
