# Generated by Django 3.0.8 on 2020-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0024_auto_20200720_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectfile',
            name='towhom',
            field=models.CharField(choices=[('srinu1234', 'srinu1234'), ('user1', 'user1')], max_length=100, null=True),
        ),
    ]
