# Generated by Django 3.0.8 on 2020-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0026_auto_20200722_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Designation',
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
