# Generated by Django 3.0.8 on 2020-07-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0027_auto_20200722_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
