# Generated by Django 3.0.8 on 2020-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0029_desig'),
    ]

    operations = [
        migrations.AddField(
            model_name='desig',
            name='role',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selectfile',
            name='towhom',
            field=models.CharField(choices=[('srinu1234', 'srinu1234'), ('user1', 'user1'), ('viswanth123', 'viswanth123'), ('user5', 'user5'), ('user10', 'user10')], max_length=100, null=True),
        ),
    ]
