# Generated by Django 3.0.8 on 2020-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0030_auto_20200722_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='desig',
            field=models.CharField(choices=[('clerk', 1), ('jto', 2), ('ad', 3), ('adet', 4), ('adg', 5), ('dir', 6), ('ddg', 7), ('other ddgs', 8), ('srddg', 9)], max_length=50, null=True),
        ),
    ]
