# Generated by Django 3.0.8 on 2020-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0032_auto_20200722_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='desig',
            field=models.CharField(choices=[(1, 'CLERK'), (2, 'JTO'), (3, 'AD'), (4, 'ADET'), (5, 'ADG'), (6, 'DIR'), (7, 'DDG'), (8, 'OTHER DDGS'), (9, 'SRDDG')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selectfile',
            name='towhom',
            field=models.CharField(choices=[('clerk', 'CLERK'), ('jto', 'JTO'), ('ad', 'AD'), ('adet', 'ADET'), ('adg', 'ADG'), ('dir', 'DIR'), ('ddg', 'DDG'), ('other ddgs', 'OTHER DDGS'), ('srddg', 'SRDDG')], max_length=100, null=True),
        ),
    ]
