# Generated by Django 3.0.8 on 2020-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0034_desig_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='notify',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
