# Generated by Django 3.0.8 on 2020-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0036_auto_20200725_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentuserdata',
            name='notify',
        ),
        migrations.AddField(
            model_name='desig',
            name='notify',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
