# Generated by Django 3.0.8 on 2020-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0037_auto_20200725_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='desig',
            field=models.CharField(choices=[('clerk', 'CLERK'), ('jto', 'JTO'), ('ad', 'AD'), ('adet', 'ADET'), ('adg', 'ADG'), ('dir', 'DIR'), ('ddg', 'DDG'), ('other ddgs', 'OTHER DDGS'), ('srddg', 'SRDDG')], max_length=50, null=True),
        ),
    ]
