# Generated by Django 3.0.8 on 2020-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0038_auto_20200727_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='notify',
            field=models.IntegerField(null=True),
        ),
    ]
