# Generated by Django 3.0.8 on 2020-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0039_auto_20200727_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desig',
            name='notify',
        ),
        migrations.AddField(
            model_name='documentuserdata',
            name='notify',
            field=models.IntegerField(null=True),
        ),
    ]
