# Generated by Django 3.0.8 on 2020-07-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0040_auto_20200727_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuserdata',
            name='notify',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
